"""Run a stratified article-learning diagnostic for the autopilot loop.

The normal autopilot intentionally explores new article pairs, so its
pre-improvement score can stay noisy even when prior gaps are retained.  This
diagnostic separates the question into slices:

* fixed_manual: stable manual cases.
* retained_replay: previously failed autopilot cases after later improvements.
* route_surface_replay: cases where route/diagnostics failed around expected
  article surfaces.
* seen_slug_new_articles: new article pairs under regulations already seen by
  autopilot, generated by the local teacher.

It never mutates the RAG artifacts.  It only writes diagnostic cases/reports.
"""

from __future__ import annotations

import argparse
import json
import random
import subprocess
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
AUTOPILOT_DIR = ROOT / "data" / "eval" / "article_autopilot"
DEFAULT_OUTPUT_DIR = AUTOPILOT_DIR / "learning_diagnostic"
DEFAULT_MANUAL_CASES = ROOT / "data" / "eval" / "manual_article_precision_gate_20260526.jsonl"
DEFAULT_SERVICE_URL = "http://127.0.0.1:8000/internal/rag/query"

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.generate_article_precision_candidates import (  # noqa: E402
    DEFAULT_MODELS,
    build_probe,
    choose_article_packets,
    load_article_catalog,
    load_autopilot_history,
    load_matrix_pairs,
    run_ollama,
)
from scripts.run_article_autopilot_improvement import classify_root_cause  # noqa: E402


def load_json(path: Path | None) -> dict[str, Any]:
    if not path or not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}


def load_jsonl(path: Path | None) -> list[dict[str, Any]]:
    if not path or not path.exists():
        return []
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def write_json(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "\n".join(json.dumps(row, ensure_ascii=False, sort_keys=True) for row in rows)
        + ("\n" if rows else ""),
        encoding="utf-8",
    )


def path_from_manifest(manifest: dict[str, Any], key: str) -> Path | None:
    raw = str((manifest.get("paths") or {}).get(key) or "").strip()
    if not raw:
        return None
    path = Path(raw)
    return path if path.is_absolute() else ROOT / path


def latest_improvement_manifests(limit: int) -> list[Path]:
    return sorted(
        AUTOPILOT_DIR.glob("article_autopilot_improvement_manifest_*.json"),
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )[:limit]


def latest_round_manifests(limit: int) -> list[Path]:
    return sorted(
        AUTOPILOT_DIR.glob("article_autopilot_manifest_*.json"),
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )[:limit]


def probe_pairs(probe: dict[str, Any]) -> set[str]:
    pairs: set[str] = set()
    for slug, articles in (probe.get("expected_articles_by_slug") or {}).items():
        for article in articles or []:
            try:
                pairs.add(f"{slug}:{int(article)}")
            except Exception:
                continue
    return pairs


def clone_case(case: dict[str, Any], slice_name: str, suffix: str) -> dict[str, Any]:
    cloned = dict(case)
    cloned["question_id"] = f"{case.get('question_id')}_{suffix}"
    cloned["diagnostic_slice"] = slice_name
    cloned["split"] = "learning_diagnostic"
    return cloned


def gather_probe_and_gate_rows(manifest_paths: list[Path]) -> tuple[dict[str, dict[str, Any]], list[dict[str, Any]]]:
    probes_by_id: dict[str, dict[str, Any]] = {}
    gate_rows: list[dict[str, Any]] = []
    for manifest_path in manifest_paths:
        manifest = load_json(manifest_path)
        if not manifest:
            continue
        for probe in load_jsonl(path_from_manifest(manifest, "probes")):
            qid = str(probe.get("question_id") or "")
            if qid:
                probes_by_id[qid] = probe
        gate = load_json(path_from_manifest(manifest, "gate"))
        for row in gate.get("rows") or []:
            enriched = dict(row)
            enriched["_source_manifest"] = str(manifest_path.relative_to(ROOT))
            gate_rows.append(enriched)
    return probes_by_id, gate_rows


def batch_manifest_paths_from_improvements(limit: int) -> list[Path]:
    paths: list[Path] = []
    seen: set[str] = set()
    for improvement_path in latest_improvement_manifests(limit):
        manifest = load_json(improvement_path)
        for raw in (manifest.get("diagnosis") or {}).get("batch_manifests") or []:
            path = Path(str(raw))
            if not path.is_absolute():
                path = ROOT / path
            marker = str(path)
            if marker in seen or not path.exists():
                continue
            seen.add(marker)
            paths.append(path)
    return paths


def fixed_manual_cases(args: argparse.Namespace) -> list[dict[str, Any]]:
    rows = load_jsonl(args.manual_cases)
    random.Random(args.seed).shuffle(rows)
    return [
        clone_case(row, "fixed_manual", f"fixed_{index:03d}")
        for index, row in enumerate(rows[: args.fixed_cases], start=1)
    ]


def retained_replay_cases(args: argparse.Namespace) -> list[dict[str, Any]]:
    manifest_paths = batch_manifest_paths_from_improvements(args.replay_cycles)
    probes_by_id, gate_rows = gather_probe_and_gate_rows(manifest_paths)
    candidates: list[tuple[float, dict[str, Any], dict[str, Any]]] = []
    for row in gate_rows:
        if row.get("transport_error") or row.get("passed"):
            continue
        qid = str(row.get("question_id") or "")
        probe = probes_by_id.get(qid)
        if not probe:
            continue
        candidates.append((float(row.get("article_points") or 0.0), row, probe))
    candidates.sort(key=lambda item: (item[0], item[1].get("question_id") or ""))
    selected = candidates[: args.replay_cases]
    return [
        clone_case(probe, "retained_replay", f"replay_{index:03d}")
        for index, (_score, _row, probe) in enumerate(selected, start=1)
    ]


def route_surface_cases(args: argparse.Namespace) -> list[dict[str, Any]]:
    manifest_paths = batch_manifest_paths_from_improvements(args.replay_cycles)
    probes_by_id, gate_rows = gather_probe_and_gate_rows(manifest_paths)
    candidates: list[tuple[int, float, dict[str, Any], dict[str, Any]]] = []
    for row in gate_rows:
        if row.get("transport_error") or row.get("passed"):
            continue
        if not row.get("unrouted_expected_article_pairs"):
            continue
        qid = str(row.get("question_id") or "")
        probe = probes_by_id.get(qid)
        if not probe:
            continue
        selected_pairs = set(row.get("selected_article_pairs") or []) | set(row.get("covered_article_pairs") or [])
        unrouted = set(row.get("unrouted_expected_article_pairs") or [])
        route_surface_only = 1 if unrouted and unrouted <= selected_pairs else 0
        candidates.append((route_surface_only, float(row.get("article_points") or 0.0), row, probe))
    candidates.sort(key=lambda item: (-item[0], -item[1], item[2].get("question_id") or ""))
    selected = candidates[: args.route_cases]
    return [
        clone_case(probe, "route_surface_replay", f"route_{index:03d}")
        for index, (_surface_only, _score, _row, probe) in enumerate(selected, start=1)
    ]


def generated_seen_slug_new_article_cases(args: argparse.Namespace) -> list[dict[str, Any]]:
    if args.seen_slug_new_cases <= 0:
        return []
    history = load_autopilot_history(args.autopilot_dir, recent_files=max(24, args.recent_history_files))
    used_pairs = set(history.get("used_pairs") or set())
    seen_slugs = {
        pair.rsplit(":", 1)[0]
        for pair in used_pairs
        if isinstance(pair, str) and ":" in pair
    }
    covered_pairs = load_matrix_pairs(args.matrix)
    articles = [
        article
        for article in load_article_catalog()
        if article.get("slug") in seen_slugs
        and article.get("pair") not in used_pairs
        and article.get("pair") not in covered_pairs
    ]
    packets = choose_article_packets(
        articles,
        covered_pairs,
        count=args.seen_slug_new_cases,
        max_articles_per_case=max(1, args.max_articles_per_case),
        seed=args.seed + 404,
        history=history,
        max_recent_slug_count=args.max_recent_slug_count,
        exclude_used_pairs=True,
    )
    models = args.model or DEFAULT_MODELS
    rows: list[dict[str, Any]] = []
    for index, packet in enumerate(packets, start=1):
        teacher_outputs = []
        prompt = __import__("scripts.generate_article_precision_candidates", fromlist=["prompt_for"]).prompt_for(packet)
        for model in models:
            try:
                teacher_outputs.append(run_ollama(model, prompt, args.ollama_url, args.teacher_timeout))
            except Exception as exc:
                teacher_outputs.append({"ok": False, "model": model, "error": str(exc), "raw": ""})
        probe = build_probe(packet, teacher_outputs, index)
        probe["diagnostic_slice"] = "seen_slug_new_articles"
        probe["question_id"] = f"{probe['question_id']}_seen_new_{index:03d}"
        probe["split"] = "learning_diagnostic"
        rows.append(probe)
    return rows


def run_gate(cases_path: Path, output_path: Path, args: argparse.Namespace, slice_name: str) -> None:
    command = [
        sys.executable,
        "scripts/run_article_precision_gate.py",
        "--cases",
        str(cases_path),
        "--output",
        str(output_path),
        "--benchmark-id",
        f"article_learning_diagnostic_{slice_name}_{args.timestamp}",
        "--retrieval-profile",
        args.retrieval_profile,
        "--service-url",
        args.service_url,
        "--timeout-seconds",
        str(args.timeout_seconds),
    ]
    completed = subprocess.run(
        command,
        cwd=ROOT,
        capture_output=True,
        text=True,
        timeout=max(600, int(args.timeout_seconds * max(2, len(load_jsonl(cases_path)) + 1))),
        check=False,
    )
    if completed.returncode:
        details = (completed.stderr or completed.stdout or "").strip()[-3000:]
        raise RuntimeError(f"gate failed for {slice_name}: {details}")


def summarize_gate(gate_path: Path) -> dict[str, Any]:
    gate = load_json(gate_path)
    summary = gate.get("summary") or {}
    rows = gate.get("rows") or []
    root_causes: Counter[str] = Counter()
    classifications: Counter[str] = Counter()
    route_surface_only = 0
    material_gap_cases = 0
    operational_rows = 0
    evaluable_rows = 0
    for row in rows:
        if row.get("transport_error"):
            operational_rows += 1
            classifications["operational issue"] += 1
            root_causes["transport_error"] += 1
            continue
        evaluable_rows += 1
        classification, cause = classify_root_cause(row)
        classifications[classification] += 1
        root_causes[cause] += 1
        unrouted = set(row.get("unrouted_expected_article_pairs") or [])
        selected = set(row.get("selected_article_pairs") or []) | set(row.get("covered_article_pairs") or [])
        if unrouted and unrouted <= selected:
            route_surface_only += 1
        if (
            row.get("missing_core_regulations")
            or row.get("missing_implementing_regulations")
            or row.get("missing_article_pairs")
        ):
            material_gap_cases += 1
    cases_total = int(summary.get("cases_total", len(rows)) or 0)
    transport_error_cases = int(summary.get("transport_error_cases", operational_rows) or 0)
    operational_only = cases_total > 0 and transport_error_cases >= cases_total
    return {
        "gate_path": str(gate_path),
        "cases_total": cases_total,
        "evaluable_cases": evaluable_rows,
        "operational_only": operational_only,
        "article_score_100": summary.get("article_score_100", 0.0),
        "pass_rate": summary.get("pass_rate", 0.0),
        "failed_cases": summary.get("failed_cases", 0),
        "transport_error_cases": transport_error_cases,
        "governing_system_rate": summary.get("governing_system_rate", 0.0),
        "implementing_regulation_rate": summary.get("implementing_regulation_rate", 0.0),
        "axis_coverage_rate": summary.get("axis_coverage_rate", 0.0),
        "root_cause_counts": dict(root_causes),
        "classification_counts": dict(classifications),
        "route_surface_only_cases": route_surface_only,
        "material_gap_cases": material_gap_cases,
        "worst_cases": summary.get("worst_cases", [])[:8],
    }


def write_markdown(path: Path, manifest: dict[str, Any]) -> None:
    lines = [
        "# Article Learning Diagnostic",
        "",
        f"- created_at: `{manifest['created_at']}`",
        f"- service_url: `{manifest['service_url']}`",
        f"- retrieval_profile: `{manifest['retrieval_profile']}`",
        "",
        "## Slice Summary",
        "",
        "| slice | cases | evaluable | operational | score | pass | material gaps | route-surface only | top causes |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
    ]
    for name, item in manifest["slices"].items():
        causes = ", ".join(f"{key}:{value}" for key, value in Counter(item.get("root_cause_counts") or {}).most_common(3))
        lines.append(
            f"| `{name}` | {item.get('cases_total')} | {item.get('evaluable_cases')} | "
            f"{item.get('transport_error_cases')} | {item.get('article_score_100')} | "
            f"{item.get('pass_rate')} | {item.get('material_gap_cases')} | "
            f"{item.get('route_surface_only_cases')} | {causes or '—'} |"
        )
    lines.extend(["", "## Interpretation", ""])
    lines.append(manifest.get("interpretation") or "")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def interpret(slice_summaries: dict[str, dict[str, Any]]) -> str:
    if slice_summaries and all(item.get("operational_only") for item in slice_summaries.values()):
        return (
            "كل الشرائح فشلت تشغيلياً فقط؛ لا توجد نتيجة صالحة للحكم على RAG. "
            "يجب تثبيت اتصال الخدمة ثم إعادة التشخيص."
        )
    fixed = slice_summaries.get("fixed_manual", {})
    replay = slice_summaries.get("retained_replay", {})
    route = slice_summaries.get("route_surface_replay", {})
    new_seen = slice_summaries.get("seen_slug_new_articles", {})
    notes: list[str] = []
    if fixed.get("operational_only"):
        notes.append("الشريحة الثابتة غير صالحة للحكم بسبب فشل تشغيلي.")
    elif float(fixed.get("pass_rate") or 0.0) >= 0.95:
        notes.append("الشريحة الثابتة مستقرة؛ لا يظهر تراجع عام في RAG.")
    elif fixed:
        notes.append("الشريحة الثابتة لا تعبر؛ هذا يشير إلى regression يجب علاجه قبل توسيع جديد.")
    if replay.get("operational_only"):
        notes.append("شريحة replay غير صالحة للحكم بسبب فشل تشغيلي.")
    elif float(replay.get("pass_rate") or 0.0) >= 0.85:
        notes.append("إعادة اختبار الفجوات القديمة جيدة؛ التحسينات تثبت غالباً.")
    elif replay:
        notes.append("إعادة اختبار الفجوات القديمة منخفضة؛ توجد مشكلة retention لا مجرد توسع أفقي.")
    if route and not route.get("operational_only") and int(route.get("route_surface_only_cases") or 0) > 0:
        notes.append("توجد حالات route-surface: مواد ظاهرة لكن التشخيص/الroute لا يحتسبها بوضوح.")
    if new_seen and not new_seen.get("operational_only"):
        replay_score = float(replay.get("article_score_100") or 0.0)
        new_score = float(new_seen.get("article_score_100") or 0.0)
        if replay_score - new_score >= 20.0:
            notes.append("الفجوة الأكبر تظهر عند مواد جديدة داخل أنظمة معروفة؛ نحتاج دعماً دلالياً عاماً للمواد لا ذاكرة أمثلة فقط.")
        else:
            notes.append("مواد الأنظمة المعروفة الجديدة ليست أضعف كثيراً من replay؛ التذبذب أقرب إلى صعوبة العينة.")
    return " ".join(notes) if notes else "لا تكفي الشرائح المتاحة لإصدار تفسير قوي."


def run(args: argparse.Namespace) -> dict[str, Any]:
    args.timestamp = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
    output_dir = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    slices: dict[str, list[dict[str, Any]]] = {
        "fixed_manual": fixed_manual_cases(args),
        "retained_replay": retained_replay_cases(args),
        "route_surface_replay": route_surface_cases(args),
        "seen_slug_new_articles": generated_seen_slug_new_article_cases(args),
    }
    slice_summaries: dict[str, dict[str, Any]] = {}
    slice_case_paths: dict[str, str] = {}
    for name, rows in slices.items():
        if not rows:
            continue
        cases_path = output_dir / f"article_learning_diagnostic_{args.timestamp}_{name}.jsonl"
        gate_path = output_dir / f"article_learning_diagnostic_gate_{args.timestamp}_{name}.json"
        write_jsonl(cases_path, rows)
        run_gate(cases_path, gate_path, args, name)
        slice_case_paths[name] = str(cases_path)
        slice_summaries[name] = summarize_gate(gate_path)

    combined_rows = [row for rows in slices.values() for row in rows]
    combined_path = output_dir / f"article_learning_diagnostic_{args.timestamp}_combined.jsonl"
    write_jsonl(combined_path, combined_rows)

    manifest = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "service_url": args.service_url,
        "retrieval_profile": args.retrieval_profile,
        "timestamp": args.timestamp,
        "cases_path": str(combined_path),
        "slice_case_paths": slice_case_paths,
        "slices": slice_summaries,
        "config": {
            "fixed_cases": args.fixed_cases,
            "replay_cases": args.replay_cases,
            "route_cases": args.route_cases,
            "seen_slug_new_cases": args.seen_slug_new_cases,
            "replay_cycles": args.replay_cycles,
            "models": args.model or DEFAULT_MODELS,
        },
    }
    manifest["interpretation"] = interpret(slice_summaries)
    manifest["decision"] = (
        "OPERATIONAL_ONLY_NO_RAG_CONCLUSION"
        if slice_summaries and all(item.get("operational_only") for item in slice_summaries.values())
        else "DIAGNOSTIC_READY"
    )
    manifest_path = output_dir / f"article_learning_diagnostic_manifest_{args.timestamp}.json"
    write_json(manifest_path, manifest)
    md_path = manifest_path.with_suffix(".md")
    write_markdown(md_path, manifest)
    manifest["manifest_path"] = str(manifest_path)
    manifest["markdown_path"] = str(md_path)
    return manifest


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--autopilot-dir", type=Path, default=AUTOPILOT_DIR)
    parser.add_argument("--manual-cases", type=Path, default=DEFAULT_MANUAL_CASES)
    parser.add_argument("--matrix", type=Path, default=ROOT / "data" / "eval" / "article_coverage_matrix_v1.json")
    parser.add_argument("--service-url", default=DEFAULT_SERVICE_URL)
    parser.add_argument("--retrieval-profile", default="jamia_recall")
    parser.add_argument("--timeout-seconds", type=float, default=180)
    parser.add_argument("--seed", type=int, default=20260602)
    parser.add_argument("--fixed-cases", type=int, default=12)
    parser.add_argument("--replay-cases", type=int, default=12)
    parser.add_argument("--route-cases", type=int, default=12)
    parser.add_argument("--seen-slug-new-cases", type=int, default=8)
    parser.add_argument("--replay-cycles", type=int, default=6)
    parser.add_argument("--max-articles-per-case", type=int, default=3)
    parser.add_argument("--recent-history-files", type=int, default=24)
    parser.add_argument("--max-recent-slug-count", type=int, default=1)
    parser.add_argument("--ollama-url", default="http://127.0.0.1:11434/api/generate")
    parser.add_argument("--teacher-timeout", type=int, default=600)
    parser.add_argument("--model", action="append", default=None)
    return parser.parse_args()


def main() -> None:
    print(json.dumps(run(parse_args()), ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
